version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: build
      args:
        - NODE_ENV=development
    command: npm run dev
    ports:
      - '8000:8000/tcp'
    volumes:
      - .:/opt:delegated
    environment:
      - NEXTAUTH_SECRET
      - NEXTAUTH_URL
      - GOOGLE_CLIENT_EMAIL
      - GOOGLE_PRIVATE_KEY
      - GOOGLE_SHEET_ID
      - ADMIN_API_TOKEN
      - VATGER_CLIENT_ID
      - VATGER_CLIENT_SECRET
      - VATGER_TOKEN_URL
      - VATGER_USER_INFO
      - VATGER_CONNECT_URL
      - USE_TEST_DB
      - DB_HOST
      - DB_PORT
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
      - DATABASE_URL
      - TRAINING_API_TOKEN
      - TRAINING_API_SOLOS_URL
      - TRAINING_API_ENDORSEMENTS_URL
      - TRAINING_API_FAMILIARIZATIONS_URL
      - GOOGLE_SHEET_ID_EDMM
      - GOOGLE_SHEET_ID_EDGG
      - GOOGLE_SHEET_ID_EDWW
      - TRAINING_CACHE_REFRESH_CRON
      - EVENT_REMINDER_CRON
      - TRAINING_API_CPTS_URL
      - DISCORD_BOT_TOKEN